simplify domain regex to filter, update cfhost.json

diff --git a/.github/workflows/update_host.yml b/.github/workflows/update_host.yml
--- a/.github/workflows/update_host.yml
+++ b/.github/workflows/update_host.yml
@@ -50,16 +50,6 @@ on:
         default: "false"
         type: "string"
     # secrets:
-    #   CF_ACCOUNT_ID:
-    #     required: true
-    #   CF_API_TOKEN:
-    #     required: true
-    #   CF_NAMESPACE_ID:
-    #     required: true
-    #   CF_WORKER_UUID:
-    #     required: false
-    #   CF_PAGE_UUID:
-    #     required: false
 
 env:
   workerName: ${{inputs.CF_WORKER_NAME || vars.CF_WORKER_NAME}}
@@ -108,8 +98,10 @@ jobs:
 
       - id: check-cfhost
         name: check cfhost, merge, backup
+        env:
+          AUTH: "Authorization:Bearer ${{env.CF_API_TOKEN}}"
         run: |
-          [ -z ${{secrets.CF_ACCOUNT_ID}} ] || [ -z $CF_API_TOKEN ] || [ -z $CF_NAMESPACE_ID ] && echo "secrets and CF_NAMESPACE_ID required!" && exit 1;
+          [ -z $CF_ACCOUNT_ID ] || [ -z $CF_API_TOKEN ] || [ -z $CF_NAMESPACE_ID ] && echo "secrets and CF_NAMESPACE_ID required!" && exit 1;
           . .github/common.sh
           touch remote.txt
 
@@ -131,7 +123,7 @@ jobs:
               echo "filter, `wc -l local.txt`" >> $GITHUB_STEP_SUMMARY
             fi
             
-            local ret=`curl -H "Authorization:Bearer $CF_API_TOKEN" "$CF_KV_API/$CFHOST"`
+            local ret=`curl -H "$AUTH" "$CF_KV_API/$CFHOST"`
             if echo "$ret"|grep error; then
               grep 'namespace not found' <<< "$ret" && exit 1 || echo "$ret"
             elif [ ! -z "$ret" ] && [ "$ret" != "[]" ]; then
@@ -139,7 +131,7 @@ jobs:
               echo "get kv $CFHOST, `wc -l remote.txt`" >> $GITHUB_STEP_SUMMARY
               
               if once_day || week_plan; then
-                local bak=`curl -H "Authorization:Bearer $CF_API_TOKEN" "$CF_KV_API/$CFHOST_BAK"`
+                local bak=`curl -H "$AUTH" "$CF_KV_API/$CFHOST_BAK"`
                 if ! echo "$bak"|grep error && [ ! -z "$bak" ] && [ "$bak" != "[]" ]; then
                   json_array_tolines $bak > remote_bak.txt
                   cat remote_bak.txt >> remote.txt
@@ -152,9 +144,10 @@ jobs:
               comm -23 <(sort remote.txt) <(sort local.txt) > tmp && mv tmp remote.txt
               # diff after manually update cfhostpat.json
               echo "diff $CFHOSTPAT_JSON ..."
-              local pat=`node $CFHOSTPAT_JS cfhostRE|sed -r 's|^/(.*)/$|\1|'`
+              local pat='^((xn--)?[a-z0-9]([a-z0-9-]{0,60}[a-z0-9])?\.){1,3}[a-z]{2,}$'
+              local cfpat=`node $CFHOSTPAT_JS cfhostRE|sed -r 's|^/(.*)/$|\1|'`
               while read -r d; do
-                [[ $d =~ $pat ]] && sed -i '/'$d'/d' remote.txt && echo delete $d from remote.txt
+                ([[ ! $d =~ $pat ]] || [[ $d =~ $cfpat ]]) && sed -i '/'$d'/d' remote.txt && echo delete $d from remote.txt
               done < remote.txt
               echo "diff local, `wc -l remote.txt`" >> $GITHUB_STEP_SUMMARY
               
@@ -165,30 +158,25 @@ jobs:
 
               if once_day || week_plan; then
                 sensitivePat=`cat $SENSITIVE_TXT`
-                sensitiveHost=
                 while read -r d; do
-                  if [[ $d =~ $sensitivePat ]]; then
-                    [ ! -z $sensitiveHost ] && sensitiveHost=$sensitiveHost,
-                    sensitiveHost=$sensitiveHost\"$d\"
-                    sed -i '/'$d'/d' remote.txt && echo remove sensitive $d from remote.txt
-                  fi
+                  [[ $d =~ $sensitivePat ]] && echo $d >> remains.txt &&  sed -i '/'$d'/d' remote.txt && echo remove sensitive $d from remote.txt
                 done < remote.txt
                 echo "filter sensitive, `wc -l remote.txt`" >> $GITHUB_STEP_SUMMARY
-
+                
+                # head -1000 remote.txt > tmp
+                # tail --lines=+1001 remote.txt >> remains.txt && mv tmp remote.txt
+                remains=`file_lines_tojson remains.txt`
                 ret=`file_lines_tojson remote.txt`
                 if [ "$ret" != "$bak" ]; then 
                   echo "kvCfhostChanged=true" >> $GITHUB_ENV;
                   # echo `comm -23 remote.txt remote_bak.txt`
-                  curl -X PUT -H "Authorization:Bearer $CF_API_TOKEN" \
-                    -d "$ret" "$CF_KV_API/$CFHOST_BAK"
+                  curl -X PUT -H "$AUTH" -d "$ret" "$CF_KV_API/$CFHOST_BAK"
                 fi
-                curl -X PUT -H "Authorization:Bearer $CF_API_TOKEN" \
-                  -d "[$sensitiveHost]" "$CF_KV_API/$CFHOST"
+                curl -X PUT -H "$AUTH" -d "$remains" "$CF_KV_API/$CFHOST"
               else
                 rst=`file_lines_tojson remote.txt`
                 if [ "$rst" != "$ret" ]; then
-                  curl -X PUT -H "Authorization:Bearer $CF_API_TOKEN" \
-                    -d "$rst" "$CF_KV_API/$CFHOST"
+                  curl -X PUT -H "$AUTH" -d "$rst" "$CF_KV_API/$CFHOST"
                 fi
               fi
             fi
